export const data = [
   {
     id: 1,
     name: "Sunset Grove Villa",
     price: 750000,
     location: "Los Angeles,CA",
     bedrooms: 3,
     bathrooms: 2,
     square_feet: 1800,
     year_built: 1995,
     type: "Single Family",
     garage: true,
   },
   {
     id: 2,
     name: "Manhattan Sky Residence",
     price: 950000,
     location: "New York,NY",
     bedrooms: 2,
     bathrooms: 2,
     square_feet: 1200,
     year_built: 2005,
     type: "Condo",
     garage: false,
   },
   {
     id: 3,
     name: "Evergreen View Estate",
     price: 625000,
     location: "Seattle,WA",
     bedrooms: 4,
     bathrooms: 2.5,
     square_feet: 2200,
     year_built: 1988,
     type: "Single Family",
     garage: true,
   },
   {
     id: 4,
     name: "Golden Gate Heights",
     price: 1200000,
     location: "San Francisco,CA",
     bedrooms: 2,
     bathrooms: 2,
     square_feet: 1100,
     year_built: 2010,
     type: "Condo",
     garage: true,
   },
   {
     id: 5,
     name: "Lone Star Ranch House",
     price: 450000,
     location: "Austin,TX",
     bedrooms: 3,
     bathrooms: 2,
     square_feet: 1900,
     year_built: 2000,
     type: "Single Family",
     garage: true,
   },
   {
     id: 6,
     name: "Historic Beacon Manor",
     price: 850000,
     location: "Boston,MA",
     bedrooms: 3,
     bathrooms: 2.5,
     square_feet: 1700,
     year_built: 1920,
     type: "Townhouse",
     garage: false,
   },
   {
     id: 7,
     name: "Rocky Mountain Retreat",
     price: 575000,
     location: "Denver,CO",
     bedrooms: 4,
     bathrooms: 3,
     square_feet: 2400,
     year_built: 2015,
     type: "Single Family",
     garage: true,
   },
   {
     id: 8,
     name: "Palm Beach Paradise",
     price: 1500000,
     location: "Miami,FL",
     bedrooms: 5,
     bathrooms: 4,
     square_feet: 3200,
     year_built: 2018,
     type: "Single Family",
     garage: true,
   },
   {
     id: 9,
     name: "Desert Oasis Home",
     price: 399000,
     location: "Phoenix,AZ",
     bedrooms: 3,
     bathrooms: 2,
     square_feet: 1600,
     year_built: 1998,
     type: "Single Family",
     garage: true,
   },
   {
     id: 10,
     name: "Rose City Townhouse",
     price: 699000,
     location: "Portland,OR",
     bedrooms: 3,
     bathrooms: 2.5,
     square_feet: 1950,
     year_built: 2008,
     type: "Townhouse",
     garage: true,
   },
   {
     id: 11,
     name: "Windy City Penthouse",
     price: 2200000,
     location: "Chicago,IL",
     bedrooms: 4,
     bathrooms: 3.5,
     square_feet: 2800,
     year_built: 2020,
     type: "Penthouse",
     garage: true,
   },
   {
     id: 12,
     name: "Music Row Manor",
     price: 525000,
     location: "Nashville,TN",
     bedrooms: 3,
     bathrooms: 2,
     square_feet: 1800,
     year_built: 2012,
     type: "Single Family",
     garage: true,
   },
   {
     id: 13,
     name: "Hollywood Hills Luxury",
     price: 3250000,
     location: "Los Angeles,CA",
     bedrooms: 6,
     bathrooms: 7,
     square_feet: 6000,
     year_built: 2018,
     type: "Mansion",
     garage: true,
   },
   {
     id: 14,
     name: "Pacific Heights Estate",
     price: 5400000,
     location: "San Francisco,CA",
     bedrooms: 5,
     bathrooms: 6,
     square_feet: 5200,
     year_built: 2009,
     type: "Mansion",
     garage: true,
   },
   {
     id: 15,
     name: "Brooklyn Brownstone",
     price: 850000,
     location: "Brooklyn,NY",
     bedrooms: 4,
     bathrooms: 3,
     square_feet: 2300,
     year_built: 1910,
     type: "Townhouse",
     garage: false,
   },
   {
     id: 16,
     name: "Malibu Beach House",
     price: 4200000,
     location: "Malibu,CA",
     bedrooms: 5,
     bathrooms: 4.5,
     square_feet: 4500,
     year_built: 2015,
     type: "Beach House",
     garage: true,
   },
   {
     id: 17,
     name: "Capitol Hill Row Home",
     price: 720000,
     location: "Washington,DC",
     bedrooms: 3,
     bathrooms: 2.5,
     square_feet: 1800,
     year_built: 1925,
     type: "Townhouse",
     garage: false,
   },
   {
     id: 18,
     name: "Buckhead Luxury Estate",
     price: 2100000,
     location: "Atlanta,GA",
     bedrooms: 5,
     bathrooms: 6,
     square_feet: 5500,
     year_built: 2010,
     type: "Single Family",
     garage: true,
   },
   {
     id: 19,
     name: "Boulder Mountain Villa",
     price: 875000,
     location: "Boulder,CO",
     bedrooms: 4,
     bathrooms: 4,
     square_feet: 3300,
     year_built: 1998,
     type: "Single Family",
     garage: true,
   },
   {
     id: 20,
     name: "French Quarter Mansion",
     price: 1600000,
     location: "New Orleans,LA",
     bedrooms: 5,
     bathrooms: 3.5,
     square_feet: 4300,
     year_built: 1875,
     type: "Mansion",
     garage: false,
   },
   {
     id: 21,
     name: "Texas Hill Country Ranch",
     price: 1050000,
     location: "San Antonio,TX",
     bedrooms: 4,
     bathrooms: 4,
     square_feet: 4000,
     year_built: 2003,
     type: "Ranch",
     garage: true,
   },
   {
     id: 22,
     name: "Naples Waterfront Villa",
     price: 2350000,
     location: "Naples,FL",
     bedrooms: 4,
     bathrooms: 5,
     square_feet: 4100,
     year_built: 2016,
     type: "Villa",
     garage: true,
   },
   {
     id: 23,
     name: "Hyde Park Loft",
     price: 925000,
     location: "Austin,TX",
     bedrooms: 2,
     bathrooms: 2,
     square_feet: 1450,
     year_built: 2014,
     type: "Loft",
     garage: false,
   },
   {
     id: 24,
     name: "Lincoln Park Mansion",
     price: 3200000,
     location: "Chicago,IL",
     bedrooms: 5,
     bathrooms: 6.5,
     square_feet: 6200,
     year_built: 2011,
     type: "Mansion",
     garage: true,
   },
   {
     id: 25,
     name: "Miami Downtown Loft",
     price: 875000,
     location: "Miami,FL",
     bedrooms: 2,
     bathrooms: 2,
     square_feet: 1600,
     year_built: 2010,
     type: "Loft",
     garage: false,
   },
   {
     id: 26,
     name: "Carmel Oceanfront Estate",
     price: 7200000,
     location: "Carmel,CA",
     bedrooms: 6,
     bathrooms: 7,
     square_feet: 6500,
     year_built: 2005,
     type: "Estate",
     garage: true,
   },
   {
     id: 27,
     name: "Savannah Historic Home",
     price: 890000,
     location: "Savannah,GA",
     bedrooms: 4,
     bathrooms: 3.5,
     square_feet: 3000,
     year_built: 1885,
     type: "Single Family",
     garage: false,
   },
   {
     id: 28,
     name: "Phoenix Desert Retreat",
     price: 625000,
     location: "Phoenix,AZ",
     bedrooms: 3,
     bathrooms: 2.5,
     square_feet: 2200,
     year_built: 2010,
     type: "Single Family",
     garage: true,
   },
   {
     id: 29,
     name: "Beacon Hill Penthouse",
     price: 1800000,
     location: "Boston,MA",
     bedrooms: 3,
     bathrooms: 3,
     square_feet: 2400,
     year_built: 2018,
     type: "Penthouse",
     garage: true,
   },
   {
     id: 30,
     name: "Salt Lake City Cabin",
     price: 750000,
     location: "Salt Lake City,UT",
     bedrooms: 4,
     bathrooms: 3,
     square_feet: 2900,
     year_built: 2007,
     type: "Cabin",
     garage: true,
   },
   {
     id: 31,
     name: "Santa Monica Bungalow",
     price: 1400000,
     location: "Santa Monica,CA",
     bedrooms: 3,
     bathrooms: 2,
     square_feet: 2000,
     year_built: 1950,
     type: "Bungalow",
     garage: true,
   },
   {
     id: 32,
     name: "Montauk Beach House",
     price: 3200000,
     location: "Montauk,NY",
     bedrooms: 5,
     bathrooms: 5,
     square_feet: 4500,
     year_built: 2015,
     type: "Beach House",
     garage: true,
   },
   {
     id: 33,
     name: "Philadelphia Row House",
     price: 625000,
     location: "Philadelphia,PA",
     bedrooms: 4,
     bathrooms: 2.5,
     square_feet: 1900,
     year_built: 1940,
     type: "Row House",
     garage: false,
   },
   {
     id: 34,
     name: "Portland Riverfront Condo",
     price: 1100000,
     location: "Portland,OR",
     bedrooms: 3,
     bathrooms: 3,
     square_feet: 2400,
     year_built: 2015,
     type: "Condo",
     garage: true,
   },
   {
     id: 35,
     name: "Aspen Ski Chalet",
     price: 2700000,
     location: "Aspen,CO",
     bedrooms: 5,
     bathrooms: 4.5,
     square_feet: 4200,
     year_built: 2013,
     type: "Chalet",
     garage: true,
   },
   {
     id: 36,
     name: "Savannah Cottage",
     price: 510000,
     location: "Savannah,GA",
     bedrooms: 3,
     bathrooms: 2,
     square_feet: 1600,
     year_built: 1910,
     type: "Cottage",
     garage: false,
   },
   {
     id: 37,
     name: "Seattle Modern Penthouse",
     price: 2400000,
     location: "Seattle,WA",
     bedrooms: 3,
     bathrooms: 3.5,
     square_feet: 2800,
     year_built: 2020,
     type: "Penthouse",
     garage: true,
   },
   {
     id: 38,
     name: "San Diego Cliffside Villa",
     price: 4500000,
     location: "San Diego,CA",
     bedrooms: 6,
     bathrooms: 5,
     square_feet: 6000,
     year_built: 2015,
     type: "Villa",
     garage: true,
   },
   {
     id: 39,
     name: "Scottsdale Desert Oasis",
     price: 1400000,
     location: "Scottsdale,AZ",
     bedrooms: 5,
     bathrooms: 4,
     square_feet: 3700,
     year_built: 2018,
     type: "Single Family",
     garage: true,
   },
   {
     id: 40,
     name: "Beverly Hills Mansion",
     price: 15000000,
     location: "Beverly Hills,CA",
     bedrooms: 8,
     bathrooms: 10,
     square_feet: 12000,
     year_built: 2021,
     type: "Mansion",
     garage: true,
   },
   {
     id: 41,
     name: "Chicago Riverwalk Condo",
     price: 1350000,
     location: "Chicago,IL",
     bedrooms: 3,
     bathrooms: 2.5,
     square_feet: 2400,
     year_built: 2012,
     type: "Condo",
     garage: true,
   },
   {
     id: 42,
     name: "Austin Lakeside Villa",
     price: 2200000,
     location: "Austin,TX",
     bedrooms: 5,
     bathrooms: 4,
     square_feet: 4300,
     year_built: 2016,
     type: "Villa",
     garage: true,
   },
]